esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  project:
    name: "Schluggi.AIOsense"
    version: "3"  # is different to the AIOsense version

logger:
  baud_rate: 0  # disable logging via UART

captive_portal:

i2c:
  scan: true

wifi:
  # Fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"

button:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
