substitutions:
  led_invert: "false"
  led_strobe_on: 50ms
  led_strobe_off: 100ms

output:
  - id: led_output
    platform: gpio
    pin:
      number: "${led_pin}"
      inverted: "${led_invert}"

light:
  - id: led
    platform: binary
    name: "LED"
    output: led_output
    icon: "mdi:led-outline"
    effects:
      - strobe:
          colors:
            - state: true
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"

esphome:
  on_boot:
    - priority: 0
      then:
        - light.turn_on: led
        - delay: 2s
        - light.turn_off: led
