output:
  - id: led_output
    platform: gpio
    pin:
      number: "${led_pin}"
      inverted: true

light:
  - id: led
    platform: binary
    name: "LED"
    output: led_output
    icon: "mdi:led-outline"

esphome:
  on_boot:
    then:
      - light.turn_on: led
      - delay: 3s
      - light.turn_off: led
