# https://esphome.io/components/light/neopixelbus.html
substitutions:
  led_strobe_on: 50ms
  led_strobe_off: 100ms

light:
  - platform: neopixelbus
    name: "LED"
    id: led
    type: "${rgb_led_type}"
    variant: WS2812X
    num_leds: 1
    pin: "${rgb_led_pin}"
    icon: "mdi:led-outline"
    effects:
      - strobe:
          colors:
            - state: true
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
      - strobe:
          name: Alarm
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
            - state: true
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              duration: "${led_strobe_on}"
            - state: false
              duration: "${led_strobe_off}"
      - pulse:

esphome:
  on_boot:
    - priority: 0
      then:
        - light.turn_on: led
        - delay: 2s
        - light.turn_off: led
