name: Python Requirements

on:
  push:
    branches: ["main"]
    paths:
      - docs/requirements.txt
  pull_request:
    branches: ["main"]
    paths:
      - docs/requirements.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: aabadie/action-install-python-requirements@v2.0.1
        with:
          requirements: docs/requirements.txt
          update-pip: true
